<?php

/**
 * @file
 * Code for the Import feature.
 */
include_once 'ildeposito_import.features.inc';

/**
 * Implements hook_feeds_presave.
 */
function ildeposito_import_feeds_presave($source, $entity, $item) {
  switch ($source->id) {
    case 'sezioni':
    case 'autori':
    case 'eventi':
    case 'articoli':
    case 'percorsi':
      if (isset($item['xpathparser:0']) && $item['xpathparser:0'] != '') {
        $files = entity_uuid_load('file', array($item['xpathparser:0']));
        if (count($files) == 1) {
          $file = reset($files);
          $entity->field_immagine[LANGUAGE_NONE][0] = (array) $file;
        }
        break;
      }
  }
}
