<?php
/**
 * @file
 * Code for the ilDeposito - Song feature.
 */

include_once 'ildeposito_song.features.inc';
include_once 'includes/ildeposito_song_pseudo_fields.inc';

/**
 * Implements hook_node_view.
 */
function ildeposito_song_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'song' && $view_mode == 'full') {

    $node->content['related_event'] = array(
      '#type' => 'item',
      '#field_name' => 'field_pseudo_related_event',
      '#label' => t('Related event:'),
      '#markup' => _ildeposito_song_related_event($node),
      '#theme_wrappers' => array('ildeposito_pseudo_field'),
      '#label_display' => 'inline',
    );

    $node->content['translation'] = array(
      '#type' => 'item',
      '#field_name' => 'field_pseudo_translation',
      '#label' => t('Translation:'),
      '#markup' => _ildeposito_song_translation($node),
      '#theme_wrappers' => array('ildeposito_pseudo_field'),
      '#label_display' => 'inline',
    );
  }
}

